sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t lincolnatal/docker-react -f Dockerfile.dev .

script:
  - docker run lincolnatal/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: elasticbeanstalk-eu-west-1-XXX
  bucket_path: "docker-react"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
      secure: "$AWS_SECRET_KEY"